### PR TITLE
Feat/settings page

### PR DESCRIPTION
**Pull request by maury91**
I've created a settings page ( like the Atom one ).

The settings page appears if you digit on the connection string "about:settings" or if you open it from the menu.
In case you open from the menu it will check if one is already open (I tried to make possible to have only 1 settings tab open, even if more than 1 doesn't conflict).

I made some minor changes:

- If you press CMD+W, before closing a tab will require a confirmation (a lot of times to me happen to press CMD+W instead of CMD+E)
- Schema filtering like the other Pull Request but:
  - The schema filter accept a mode (Whitelist | Blacklist)
  - The schema filter accept a regexp (case insensitive)
- I add the build scripts to the npm scripts, in this way is possible to build the app without installing electron-packager globally (or the other packages)

screen shot 2017-03-17 at 23 21 42

### CODE REVIEW

**Comment by sasha-alias** [comment]
@maury91 Great contribution!
Thank you very much for your work on this PR and the others you've sent recently.
Really appreciated!

**Comment by maury91** [comment]
@sasha-alias  You welcome, I should thank you for the entire app, it make my job easier

**Comment by sasha-alias** [comment]
hey @maury91 
for some reason settings tab keyboard shortcut `Cmd+,` doesn't work for me .
Trying to understand if it's my local issue.. Does it work for you?

**Comment by maury91** [comment]
hi @sasha-alias 
unfortunately, doesn't work neither on mine, I wasn't able to find any information online, so I just leave it as a placeholder to know which one should be the usual combination

**Comment by sasha-alias** [comment]
it looks like Editor captures this keys combination and doesn't allow to propagate further, when focus is out of the editor it works.

**Comment by sasha-alias** [comment]
found https://github.com/sasha-alias/sqltabs/commit/29234f093eb40075183b343af27143a10e9824c7

thanks for the help

**Pull request merged**
